
import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getFirestore, doc, getDoc, setDoc, updateDoc, deleteDoc, collection, addDoc, getDocs, onSnapshot, query, orderBy, where, serverTimestamp, arrayRemove } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
import { getAuth, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
const firebaseConfig={apiKey:"AIzaSyD80d4bZpZZp0JRZeaBwQKG5GapwLJVki8",authDomain:"kalb-message.firebaseapp.com",projectId:"kalb-message",storageBucket:"kalb-message.firebasestorage.app",messagingSenderId:"139873273901",appId:"1:139873273901:web:c7c079d385daeb3401d0a4",measurementId:"G-C9S0K1SG0D"};
const appSec=getApps().length?getApps()[0]:initializeApp(firebaseConfig);
const dbSec=getFirestore(appSec);
const authSec=getAuth(appSec);
let secUser=null;
let secProfile=null;
let secUsers=[];
let secReports=[];
let myReports=[];
let adminReportFilter='open';
let unsubMyReports=null;
let unsubAdminReports=null;
let pinUnlockedForSession=false;
const ADMIN_EMAIL='kalbhatgamer@gmail.com';
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function fmt(ts){try{if(ts&&ts.seconds)return new Date(ts.seconds*1000).toLocaleString();}catch(e){} return 'Just now';}
function isAdmin(){return !!secUser && String(secUser.email||'').toLowerCase()===ADMIN_EMAIL.toLowerCase();}
function pinKey(){return secUser?`kalbAppPin_${secUser.uid}`:'kalbAppPin_guest';}
function trustKey(){return secUser?`kalbTrustedDevices_${secUser.uid}`:'kalbTrustedDevices_guest';}
function loginKey(){return secUser?`kalbLoginActivity_${secUser.uid}`:'kalbLoginActivity_guest';}
function reportStatus(text,bad=false){const el=document.getElementById('securityReportStatus'); if(el)el.innerHTML=`<div class="notice ${bad?'err':''}">${esc(text)}</div>`;}
function pinStatus(text,bad=false){const el=document.getElementById('kalbPinUnlockStatus'); if(el)el.innerHTML=`<div class="notice ${bad?'err':''}">${esc(text)}</div>`;}
function getDeviceId(){let id=localStorage.getItem('kalbDeviceId'); if(!id){id='dev_'+Math.random().toString(36).slice(2)+Date.now().toString(36); localStorage.setItem('kalbDeviceId',id);} return id;}
function deviceName(){const ua=navigator.userAgent||''; let browser='Browser'; if(/Chrome/i.test(ua))browser='Chrome'; else if(/Firefox/i.test(ua))browser='Firefox'; else if(/Safari/i.test(ua))browser='Safari'; else if(/Edg/i.test(ua))browser='Edge'; const platform=navigator.platform||'Device'; return `${browser} on ${platform}`;}
function loadLocalArray(key){try{return JSON.parse(localStorage.getItem(key)||'[]')||[]}catch(e){return[]}}
function saveLocalArray(key,arr){localStorage.setItem(key,JSON.stringify(arr.slice(0,50)));}
function addLoginActivity(){if(!secUser)return; const key=loginKey(); const list=loadLocalArray(key); const item={id:'login_'+Date.now(),deviceId:getDeviceId(),device:deviceName(),time:Date.now(),email:secUser.email||''}; if(!list.some(x=>Date.now()-Number(x.time||0)<60000 && x.deviceId===item.deviceId)){list.unshift(item); saveLocalArray(key,list);} renderLoginActivity();}
async function loadProfile(){if(!secUser)return; try{const s=await getDoc(doc(dbSec,'users',secUser.uid)); secProfile=s.exists()?s.data():{};}catch(e){secProfile={};}}
async function loadUsers(){try{const snap=await getDocs(collection(dbSec,'users')); secUsers=[]; snap.forEach(d=>secUsers.push({uid:d.id,...d.data()}));}catch(e){console.warn('users load failed',e);}}
function findUser(id){return secUsers.find(u=>u.uid===id || u.kalbId===id || u.kalbID===id || String(u.email||'').toLowerCase()===String(id||'').toLowerCase());}
function renderSecurityTiles(){const pin=document.getElementById('securityPinStatus'); if(pin)pin.textContent=localStorage.getItem(pinKey())?'PIN: On':'PIN: Off'; const bc=document.getElementById('securityBlockedCount'); if(bc)bc.textContent=((secProfile&&secProfile.blockedUsers)||[]).length+' blocked'; const rc=document.getElementById('securityReportCount'); if(rc)rc.textContent=(myReports||[]).length+' reports';}
function renderBlockedUsers(){const box=document.getElementById('securityBlockedUsersBox'); if(!box)return; const ids=(secProfile&&secProfile.blockedUsers)||[]; if(!ids.length){box.innerHTML='<div class="empty">No blocked users.</div>'; return;} box.innerHTML=ids.map(uid=>{const u=findUser(uid)||{uid,name:'Unknown User',email:''}; return `<div class="security-list-item"><div class="security-list-icon">🚫</div><div><b>${esc(u.name||u.username||'User')}</b><p>${esc(u.kalbId||u.kalbID||u.uid)} • ${esc(maskEmail(u.email||''))}</p></div><button class="btn small green" onclick="kalbSecurityUnblock('${esc(uid)}')">Unblock</button></div>`}).join('');}
function maskEmail(email){email=String(email||''); if(!email.includes('@'))return email; const [a,d]=email.split('@'); return (a.slice(0,2)+'***')+'@'+d.replace(/^(.{2}).*?(\..*)?$/,(m,x,y)=>x+'***'+(y||''));}
function renderLoginActivity(){const box=document.getElementById('securityLoginActivityBox'); if(!box)return; const list=loadLocalArray(loginKey()); box.innerHTML=list.length?list.map(x=>`<div class="security-list-item"><div class="security-list-icon">📱</div><div><b>${esc(x.device||'Device')}</b><p>${new Date(Number(x.time||Date.now())).toLocaleString()} • ${esc(maskEmail(x.email||''))}</p></div><span class="report-status-pill">Login</span></div>`).join(''):'<div class="empty">No login activity yet.</div>';}
function renderTrustedDevices(){const box=document.getElementById('securityTrustedDevicesBox'); if(!box)return; const list=loadLocalArray(trustKey()); box.innerHTML=list.length?list.map(x=>`<div class="security-list-item"><div class="security-list-icon">✅</div><div><b>${esc(x.device||'Trusted device')}</b><p>${new Date(Number(x.time||Date.now())).toLocaleString()}${x.deviceId===getDeviceId()?' • Current device':''}</p></div><button class="btn small red" onclick="kalbRemoveTrustedDevice('${esc(x.deviceId)}')">Remove</button></div>`).join(''):'<div class="empty">No trusted devices yet. You can trust this browser.</div>';}
function renderTargetSelect(){const sel=document.getElementById('securityReportTargetSelect'); if(!sel)return; const opts=['<option value="">Select target or type ID below</option>'].concat(secUsers.filter(u=>u.uid!==secUser?.uid).slice(0,150).map(u=>`<option value="${esc(u.uid)}">${esc(u.name||u.username||'User')} • ${esc(u.kalbId||u.uid)}</option>`)); sel.innerHTML=opts.join(''); sel.onchange=()=>{const id=document.getElementById('securityReportTargetId'); if(id&&sel.value)id.value=sel.value;};}
function renderMyReports(){const box=document.getElementById('securityMyReportsBox'); if(!box)return; if(!myReports.length){box.innerHTML='<div class="empty">No reports sent yet.</div>'; return;} box.innerHTML=myReports.slice(0,30).map(r=>`<div class="admin-report-card ${esc(r.status||'open')}"><div class="admin-report-head"><b>🚩 ${esc(r.type||r.targetType||'Report')}</b><span class="report-status-pill">${esc(r.status||'open')}</span></div><div class="admin-report-body"><p><b>Reason:</b> ${esc(r.reason||'')}</p><p class="muted">Target: ${esc(r.targetName||r.targetId||r.targetUid||r.postId||'')} • ${fmt(r.createdAt)}</p>${r.details?`<p>${esc(r.details)}</p>`:''}</div></div>`).join('');}
function renderPrivacyCheckup(){const el=document.getElementById('securityPrivacyStatus'); if(!el)return; const blocked=((secProfile&&secProfile.blockedUsers)||[]).length; const hidden=secProfile&&secProfile.hideOnline===true; const privateProfile=secProfile&&secProfile.privateProfile===true; el.innerHTML=`<span class="${hidden?'security-good':'security-warn'}">Online status: ${hidden?'Hidden':'Visible'}</span><br><span class="${privateProfile?'security-good':'security-warn'}">Profile: ${privateProfile?'Private':'Public'}</span><br><span class="security-good">Blocked users: ${blocked}</span>`;}
async function refreshSecurity(){if(!secUser)return; await loadProfile(); await loadUsers(); renderSecurityTiles(); renderBlockedUsers(); renderTargetSelect(); renderLoginActivity(); renderTrustedDevices(); renderPrivacyCheckup();}
function showPinOverlay(){const ov=document.getElementById('kalbAppPinOverlay'); if(ov){ov.classList.add('active'); const inp=document.getElementById('kalbUnlockPinInput'); if(inp){inp.value=''; setTimeout(()=>inp.focus(),80);}}}
function hidePinOverlay(){const ov=document.getElementById('kalbAppPinOverlay'); if(ov)ov.classList.remove('active');}
function maybeRequirePin(){if(!secUser)return; const pin=localStorage.getItem(pinKey()); if(pin && !pinUnlockedForSession){setTimeout(showPinOverlay,500);}}
window.kalbSetAppPin=function(){if(!secUser)return alert('Login first.'); const input=document.getElementById('securityPinInput'); const pin=String(input?.value||'').trim(); if(!/^\d{4}$/.test(pin))return alert('Enter exactly 4 digits.'); localStorage.setItem(pinKey(),btoa(pin)); if(input)input.value=''; pinUnlockedForSession=true; renderSecurityTiles(); alert('App PIN enabled on this device.');};
window.kalbDisableAppPin=function(){if(!secUser)return; const saved=localStorage.getItem(pinKey()); if(saved){const p=prompt('Enter current PIN to disable:'); if(!p || btoa(p)!==saved)return alert('Wrong PIN.');} localStorage.removeItem(pinKey()); pinUnlockedForSession=true; renderSecurityTiles(); alert('App PIN disabled.');};
window.kalbLockNow=function(){if(!localStorage.getItem(pinKey()))return alert('Set a PIN first.'); pinUnlockedForSession=false; showPinOverlay();};
window.kalbUnlockWithPin=function(){const saved=localStorage.getItem(pinKey()); const p=String(document.getElementById('kalbUnlockPinInput')?.value||''); if(saved && btoa(p)===saved){pinUnlockedForSession=true; hidePinOverlay(); pinStatus('');} else pinStatus('Wrong PIN.',true);};
window.kalbForgotPinLogout=async function(){try{await signOut(authSec);}catch(e){} localStorage.removeItem(pinKey()); hidePinOverlay(); alert('Logged out. PIN for this device was cleared.');};
window.kalbTrustCurrentDevice=function(){if(!secUser)return; const key=trustKey(); const list=loadLocalArray(key).filter(x=>x.deviceId!==getDeviceId()); list.unshift({deviceId:getDeviceId(),device:deviceName(),time:Date.now()}); saveLocalArray(key,list); renderTrustedDevices();};
window.kalbRemoveCurrentTrustedDevice=function(){window.kalbRemoveTrustedDevice(getDeviceId());};
window.kalbRemoveTrustedDevice=function(deviceId){const key=trustKey(); const list=loadLocalArray(key).filter(x=>x.deviceId!==deviceId); saveLocalArray(key,list); renderTrustedDevices();};
window.kalbRunPrivacyCheckup=function(){renderPrivacyCheckup(); alert('Privacy checkup updated.');};
window.kalbSecurityUnblock=async function(uid){if(!secUser)return; try{if(typeof window.unblockUser==='function'){await window.unblockUser(uid);}else{await updateDoc(doc(dbSec,'users',secUser.uid),{blockedUsers:arrayRemove(uid)});} await refreshSecurity();}catch(e){alert(e.message||'Unblock failed.');}};
async function createReport(data){if(!secUser)throw new Error('Login first.'); const reporter=secProfile||{}; const payload={type:data.type||data.targetType||'other',targetType:data.targetType||data.type||'other',targetId:data.targetId||'',targetUid:data.targetUid||'',postId:data.postId||'',chatId:data.chatId||'',groupId:data.groupId||'',channelId:data.channelId||'',targetName:data.targetName||'',reason:data.reason||'Other',details:data.details||'',status:'open',priority:data.priority||'medium',uid:secUser.uid,reporterUid:secUser.uid,email:secUser.email||'',reporterName:reporter.name||secUser.displayName||'User',createdAt:serverTimestamp(),updatedAt:serverTimestamp()}; await addDoc(collection(dbSec,'reports'),payload); return payload;}
window.kalbSubmitSecurityReport=async function(){try{const type=document.getElementById('securityReportType')?.value||'other'; const targetId=(document.getElementById('securityReportTargetId')?.value||'').trim(); const reason=document.getElementById('securityReportReason')?.value||'Other'; const details=(document.getElementById('securityReportDetails')?.value||'').trim(); const target=findUser(targetId); if(!targetId && ['user','post','chat','group','channel'].includes(type))return reportStatus('Select or enter a target ID first.',true); await createReport({type,targetType:type,targetId,targetUid:type==='user'?(target?.uid||targetId):'',postId:type==='post'?targetId:'',chatId:type==='chat'?targetId:'',groupId:type==='group'?targetId:'',channelId:type==='channel'?targetId:'',targetName:target?(target.name||target.email||target.uid):'',reason,details}); document.getElementById('securityReportDetails').value=''; reportStatus('Report submitted. Admin can review it.');}catch(e){reportStatus(e.message||'Report failed.',true);}};
window.reportProfile=async function(uid){try{const u=findUser(uid); const reason=prompt('Why are you reporting this profile?','Spam or fake account'); if(!reason)return; await createReport({type:'profile',targetType:'user',targetId:uid,targetUid:uid,targetName:u?(u.name||u.email||uid):uid,reason}); alert('Profile reported.');}catch(e){alert(e.message||'Report failed.');}};
window.reportUser=window.reportProfile;
window.reportPost=async function(postId){try{const reason=prompt('Why are you reporting this post?','Unsafe content'); if(!reason)return; await createReport({type:'post',targetType:'post',targetId:postId,postId,reason}); alert('Post reported.');}catch(e){alert(e.message||'Report failed.');}};
window.reportCurrentChat=async function(){try{let id=''; let name=''; try{id=window.currentChatId||''; name=(window.currentChatUser&&window.currentChatUser.name)||'';}catch(e){} const reason=prompt('Why are you reporting this chat?','Abuse or harassment'); if(!reason)return; await createReport({type:'chat',targetType:'chat',targetId:id,chatId:id,targetName:name,reason}); alert('Chat reported.');}catch(e){alert(e.message||'Report failed.');}};
window.kalbReportGroup=async function(groupId){try{const reason=prompt('Why are you reporting this group?','Unsafe content'); if(!reason)return; await createReport({type:'group',targetType:'group',targetId:groupId,groupId,reason}); alert('Group reported.');}catch(e){alert(e.message||'Report failed.');}};
window.kalbReportChannel=async function(channelId){try{const reason=prompt('Why are you reporting this channel?','Unsafe content'); if(!reason)return; await createReport({type:'channel',targetType:'channel',targetId:channelId,channelId,reason}); alert('Channel reported.');}catch(e){alert(e.message||'Report failed.');}};
function listenMyReports(){if(unsubMyReports){try{unsubMyReports();}catch(e){}} if(!secUser)return; try{const q=query(collection(dbSec,'reports'),where('uid','==',secUser.uid)); unsubMyReports=onSnapshot(q,snap=>{myReports=[]; snap.forEach(d=>myReports.push({id:d.id,...d.data()})); myReports.sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)); renderMyReports(); renderSecurityTiles();},e=>console.warn('my reports listen failed',e));}catch(e){console.warn(e);}}
function listenAdminReports(){if(unsubAdminReports){try{unsubAdminReports();}catch(e){}} if(!isAdmin())return; try{unsubAdminReports=onSnapshot(query(collection(dbSec,'reports'),orderBy('createdAt','desc')),snap=>{secReports=[]; snap.forEach(d=>secReports.push({id:d.id,...d.data()})); renderAdminReports();},e=>console.warn('admin reports listen failed',e));}catch(e){console.warn(e);}}
function renderAdminReports(){const box=document.getElementById('kalbAdminReportReviewBox'); if(!box)return; if(!isAdmin()){box.innerHTML='<div class="empty">Admin only.</div>'; return;} let list=secReports||[]; if(adminReportFilter==='open')list=list.filter(r=>(r.status||'open')!=='resolved'); if(!list.length){box.innerHTML='<div class="empty">No reports found.</div>'; return;} box.innerHTML=list.slice(0,120).map(r=>{const status=r.status||'open'; const type=r.targetType||r.type||'report'; const tid=r.targetUid||r.postId||r.groupId||r.channelId||r.chatId||r.targetId||''; return `<div class="admin-report-card ${esc(status)}"><div class="admin-report-head"><b>🚩 ${esc(type)} report</b><span><span class="report-priority ${(r.priority||'medium')==='high'?'high':'medium'}">${esc(r.priority||'medium')}</span><span class="report-status-pill">${esc(status)}</span></span></div><div class="admin-report-body"><p><b>Reason:</b> ${esc(r.reason||'')}</p>${r.details?`<p>${esc(r.details)}</p>`:''}<p class="muted">Target: ${esc(tid||r.targetName||'')} • By: ${esc(maskEmail(r.email||''))} • ${fmt(r.createdAt)}</p></div><div class="security-actions">${r.targetUid?`<button class="btn small red" onclick="kalbAdminBanReportedUser('${esc(r.targetUid)}')">Ban User</button><button class="btn small green" onclick="kalbAdminUnbanReportedUser('${esc(r.targetUid)}')">Unban</button>`:''}${r.postId?`<button class="btn small red" onclick="kalbAdminDeleteReportedPost('${esc(r.postId)}')">Delete Post</button>`:''}${r.groupId?`<button class="btn small red" onclick="kalbAdminDeleteReportedGroup('${esc(r.groupId)}')">Delete Group</button>`:''}${r.channelId?`<button class="btn small red" onclick="kalbAdminDeleteReportedChannel('${esc(r.channelId)}')">Delete Channel</button>`:''}<button class="btn small" onclick="kalbAdminSetReportStatus('${esc(r.id)}','reviewing')">Reviewing</button><button class="btn small green" onclick="kalbAdminSetReportStatus('${esc(r.id)}','resolved')">Resolve</button><button class="btn small red" onclick="kalbAdminDeleteReportFinal('${esc(r.id)}')">Delete Report</button></div></div>`;}).join('');}
window.kalbAdminRenderReports=renderAdminReports;
window.kalbAdminFilterReports=function(f){adminReportFilter=f||'open'; renderAdminReports();};
window.kalbAdminSetReportStatus=async function(id,status){if(!isAdmin())return alert('Admin only.'); await setDoc(doc(dbSec,'reports',id),{status,updatedAt:serverTimestamp()},{merge:true});};
window.kalbAdminDeleteReportFinal=async function(id){if(!isAdmin())return alert('Admin only.'); if(confirm('Delete this report?'))await deleteDoc(doc(dbSec,'reports',id));};
window.kalbAdminBanReportedUser=async function(uid){if(!isAdmin())return alert('Admin only.'); await setDoc(doc(dbSec,'users',uid),{banned:true},{merge:true}); alert('User banned.');};
window.kalbAdminUnbanReportedUser=async function(uid){if(!isAdmin())return alert('Admin only.'); await setDoc(doc(dbSec,'users',uid),{banned:false},{merge:true}); alert('User unbanned.');};
window.kalbAdminDeleteReportedPost=async function(id){if(!isAdmin())return alert('Admin only.'); if(confirm('Delete reported post?'))await deleteDoc(doc(dbSec,'posts',id));};
window.kalbAdminDeleteReportedGroup=async function(id){if(!isAdmin())return alert('Admin only.'); if(confirm('Delete reported group?'))await deleteDoc(doc(dbSec,'groups',id));};
window.kalbAdminDeleteReportedChannel=async function(id){if(!isAdmin())return alert('Admin only.'); if(confirm('Delete reported channel?'))await deleteDoc(doc(dbSec,'channels',id));};
function ensureSecuritySettingsButton(){const settings=document.getElementById('settingsPage'); if(!settings||document.getElementById('securityCenterQuickBtn'))return; const card=[...settings.querySelectorAll('.card')].find(c=>/Settings/i.test(c.textContent||'')); if(card){const row=document.createElement('div'); row.className='setting-row'; row.innerHTML='<b>Security Center</b><p class="muted">PIN lock, block list, login activity, trusted devices, and reports.</p><div class="actions"><button id="securityCenterQuickBtn" class="btn small green" onclick="openPage(\'securityCenterPage\')">Open Security Center</button></div>'; card.insertBefore(row, card.querySelector('.btn.red')||null);}}
function patchOpenPage(){if(window.__kalbSecurityOpenPatched)return; const old=window.openPage; if(typeof old==='function'){window.openPage=function(id,navEl){const res=old.apply(this,arguments); if(id==='securityCenterPage')setTimeout(()=>refreshSecurity(),60); if(id==='adminPage')setTimeout(()=>renderAdminReports(),100); return res;}; window.__kalbSecurityOpenPatched=true;}}
function init(){ensureSecuritySettingsButton(); patchOpenPage(); renderLoginActivity(); renderTrustedDevices(); renderSecurityTiles(); setTimeout(()=>refreshSecurity(),500);}
onAuthStateChanged(authSec,async user=>{secUser=user; pinUnlockedForSession=false; if(user){await loadProfile(); addLoginActivity(); await loadUsers(); init(); listenMyReports(); listenAdminReports(); maybeRequirePin();}else{secProfile=null; secUsers=[]; secReports=[]; myReports=[]; renderSecurityTiles();}});
window.addEventListener('DOMContentLoaded',init);
setTimeout(init,1200);
