
import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { getFirestore, doc, getDoc, setDoc, serverTimestamp, increment, arrayUnion } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyD80d4bZpZZp0JRZeaBwQKG5GapwLJVki8",authDomain:"kalb-message.firebaseapp.com",projectId:"kalb-message",storageBucket:"kalb-message.firebasestorage.app",messagingSenderId:"139873273901",appId:"1:139873273901:web:c7c079d385daeb3401d0a4",measurementId:"G-C9S0K1SG0D"};
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig);
const auth=getAuth(app); const db=getFirestore(app);
const DAY_MS=24*60*60*1000;
const REWARDS=[
  {id:'coins20', label:'+20 Coins', icon:'🪙', type:'coins', amount:20, desc:'Adds 20 Kalb Coins to your wallet.'},
  {id:'xp50', label:'+50 XP', icon:'⚡', type:'xp', amount:50, desc:'Adds XP to your level progress.'},
  {id:'stickerPack', label:'Sticker Pack', icon:'🎟️', type:'sticker', packId:'premium_neon', desc:'Unlocks Neon premium sticker pack.'},
  {id:'themeTrial', label:'Theme Trial', icon:'🎨', type:'theme', themeId:'anime', desc:'Adds a 24 hour Anime Glow theme trial token.'},
  {id:'profileFrame', label:'Profile Frame', icon:'🏆', type:'frame', rewardId:'gold_frame', desc:'Unlocks the golden profile frame reward.'},
  {id:'mystery', label:'Mystery', icon:'🎁', type:'mystery', desc:'Random bonus reward.'},
  {id:'coins100', label:'+100 Coins', icon:'💰', type:'coins', amount:100, desc:'Lucky big Kalb Coins win.'},
  {id:'xp80', label:'+80 XP', icon:'🚀', type:'xp', amount:80, desc:'Big XP boost for your level.'}
];
let spinBusy=false; let spinTimer=null; let wheelRotation=0;
function el(id){return document.getElementById(id)}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function n(v){const x=Number(v||0);return Number.isFinite(x)?Math.max(0,Math.floor(x)):0}
function fmt(ms){ms=Math.max(0,Number(ms||0));const h=Math.floor(ms/3600000),m=Math.floor((ms%3600000)/60000),s=Math.floor((ms%60000)/1000);return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function lsKey(uid){return 'kalbDailySpinLastAt_'+(uid||auth.currentUser?.uid||'guest')}
function localLast(uid){try{return Number(localStorage.getItem(lsKey(uid))||0)||0}catch(e){return 0}}
function saveLocalLast(uid,ms){try{localStorage.setItem(lsKey(uid),String(ms||Date.now()))}catch(e){}}
async function getMe(){const u=auth.currentUser;if(!u)return null;try{const s=await getDoc(doc(db,'users',u.uid));return s.exists()?{uid:s.id,...s.data()}:{};}catch(e){console.warn('spin profile read failed',e);return {kalbLastSpinAt:localLast(u.uid)}}}
function lastAtFrom(me,uid){let v=me?.kalbLastSpinAt||0;if(v&&typeof v.toMillis==='function')v=v.toMillis();v=n(v);return Math.max(v,localLast(uid));}
function status(msg,bad=false){const box=el('kalbSpinStatus');if(box)box.innerHTML=msg?`<div class="notice ${bad?'err':''}">${msg}</div>`:'';}
function updateCountdown(lastAt){const btn=el('kalbDailySpinBtn');const cd=el('kalbSpinCountdown');const ready=el('kalbSpinReadyText');const remain=(lastAt+DAY_MS)-Date.now();const can=remain<=0;if(btn)btn.disabled=!can||spinBusy;if(cd)cd.textContent=can?'Ready now':fmt(remain);if(ready)ready.textContent=can?'Spin available':'Next spin in';return can;}
function kalbSpinWaitUser(){if(auth.currentUser)return Promise.resolve(auth.currentUser);return new Promise(resolve=>{let done=false;const unsub=onAuthStateChanged(auth,u=>{if(done)return;done=true;try{unsub();}catch(e){}resolve(u||auth.currentUser||null);});setTimeout(()=>{if(done)return;done=true;try{unsub();}catch(e){}resolve(auth.currentUser||null);},2500);});}
async function renderSpin(){injectSpin();const u=auth.currentUser||await kalbSpinWaitUser();if(!u){updateCountdown(Date.now());status('Login first to use Daily Spin Wheel.',true);return;}const me=await getMe();const last=lastAtFrom(me,u.uid);const lastText=el('kalbSpinLastText');if(lastText){const r=me?.kalbLastSpinReward||localStorage.getItem('kalbDailySpinLastReward_'+u.uid)||'No spin yet';lastText.innerHTML=last?`Last reward: <b>${esc(r)}</b><br>Last spin: ${new Date(last).toLocaleString()}`:'No spin yet. Your first spin is ready.';}updateCountdown(last);if(spinTimer)clearInterval(spinTimer);spinTimer=setInterval(()=>updateCountdown(last),1000);}
function injectSpin(){const settings=el('settingsPage');if(!settings||el('kalbDailySpinCard'))return;const card=document.createElement('div');card.className='card kalb-spin-card';card.id='kalbDailySpinCard';card.innerHTML=`<div class="kalb-spin-head"><div><h2>🎡 Daily Spin Wheel</h2><p class="muted">Spin once every 24 hours from your last spin and win coins, XP, stickers, theme trial, profile frame or mystery reward.</p></div><span class="kalb-spin-pill"><span id="kalbSpinReadyText">Loading</span>: <span id="kalbSpinCountdown">--:--:--</span></span></div><div class="kalb-spin-layout"><div class="kalb-wheel-wrap"><div class="kalb-wheel-pointer"></div><div id="kalbDailyWheel" class="kalb-wheel"></div><div class="kalb-wheel-labels">${REWARDS.map(r=>`<span title="${esc(r.label)}">${r.icon}</span>`).join('')}</div></div><div class="kalb-spin-info"><div class="kalb-spin-prizes">${REWARDS.map(r=>`<div class="kalb-spin-prize"><b>${r.icon} ${esc(r.label)}</b>${esc(r.desc)}</div>`).join('')}</div><div class="kalb-spin-actions"><button id="kalbDailySpinBtn" class="btn small green" onclick="kalbSpinDailyWheel()">Spin Now</button><button class="btn small" onclick="kalbRenderDailySpinWheel()">Refresh</button></div><div id="kalbSpinLastText" class="kalb-spin-last">Loading spin info...</div><div id="kalbSpinStatus" class="kalb-spin-status"></div></div></div>`;const coins=el('kalbCoinsWalletCard');if(coins)coins.insertAdjacentElement('afterend',card);else settings.insertBefore(card,settings.firstElementChild||null);}
function rewardPatch(reward,now){const patch={kalbLastSpinAt:now,kalbLastSpinReward:`${reward.icon} ${reward.label}`,kalbSpinCount:increment(1),kalbSpinUpdatedAt:serverTimestamp()};let message=`You won ${reward.icon} ${reward.label}!`;if(reward.type==='coins'){patch.kalbCoins=increment(reward.amount);message+=` +${reward.amount} coins added.`;}else if(reward.type==='xp'){patch.kalbXP=increment(reward.amount);patch.kalbAchievementFlags={spinPlayer:true};message+=` +${reward.amount} XP added.`;}else if(reward.type==='sticker'){patch.ownedStickerPacks=arrayUnion(reward.packId);message+=' Premium sticker pack unlocked.';}else if(reward.type==='theme'){const exp=now+DAY_MS;patch.kalbThemeTrial={themeId:reward.themeId,expiresAt:exp,createdAt:now};try{localStorage.setItem('kalbSpinThemeTrial',JSON.stringify(patch.kalbThemeTrial));localStorage.setItem('kalbInstalledMarketplaceThemes',JSON.stringify(Array.from(new Set([...(JSON.parse(localStorage.getItem('kalbInstalledMarketplaceThemes')||'[]')),reward.themeId]))));}catch(e){}message+=' Theme trial token added for 24 hours.';}else if(reward.type==='frame'){patch.ownedRewards=arrayUnion(reward.rewardId);message+=' Profile frame reward unlocked.';}else if(reward.type==='mystery'){patch.kalbCoins=increment(75);patch.kalbXP=increment(60);message='Mystery reward! +75 coins and +60 XP added.';}return {patch,message};}
window.kalbSpinDailyWheel=async function(){if(spinBusy)return;const u=auth.currentUser||await kalbSpinWaitUser();if(!u)return alert('Login first.');spinBusy=true;try{const me=await getMe();const last=lastAtFrom(me,u.uid);const remain=(last+DAY_MS)-Date.now();if(remain>0){spinBusy=false;updateCountdown(last);return status('You can spin again after '+fmt(remain)+'.',true);}const reward=REWARDS[Math.floor(Math.random()*REWARDS.length)];const idx=REWARDS.findIndex(r=>r.id===reward.id);const wheel=el('kalbDailyWheel');wheelRotation += 360*6 + (360 - (idx*45 + 22));if(wheel)wheel.style.transform=`rotate(${wheelRotation}deg)`;const labelLayer=document.querySelector('#kalbDailySpinCard .kalb-wheel-labels');if(labelLayer)labelLayer.style.transform=`rotate(${wheelRotation}deg)`;status('Spinning...');const now=Date.now();setTimeout(async()=>{try{const {patch,message}=rewardPatch(reward,now);await setDoc(doc(db,'users',u.uid),patch,{merge:true});saveLocalLast(u.uid,now);localStorage.setItem('kalbDailySpinLastReward_'+u.uid,`${reward.icon} ${reward.label}`);status(`<div class="kalb-spin-win-pop">${esc(message)}</div>`);spinBusy=false;try{window.kalbRenderCoinsSystem&&window.kalbRenderCoinsSystem()}catch(e){}try{window.kalbRenderAchievementsSystem&&window.kalbRenderAchievementsSystem()}catch(e){}try{window.renderKalbStickerStore&&window.renderKalbStickerStore()}catch(e){}renderSpin();}catch(e){console.error(e);status(esc(e.message||'Spin reward could not be saved. Check Firebase rules.'),true);spinBusy=false;renderSpin();}},4300);}catch(e){console.error(e);status(esc(e.message||'Spin failed.'),true);spinBusy=false;}};
window.kalbRenderDailySpinWheel=function(){renderSpin().catch(e=>console.warn(e));};
function boot(){injectSpin();renderSpin().catch(e=>console.warn(e));}
function wrapOpenPage(){if(window.openPage&&!window.openPage.__dailySpinWrapped){const old=window.openPage;window.openPage=function(id,nav){const r=old.apply(this,arguments);if(id==='settingsPage')setTimeout(boot,180);return r;};window.openPage.__dailySpinWrapped=true;}}
document.addEventListener('DOMContentLoaded',()=>{injectSpin();wrapOpenPage();setTimeout(boot,700)});window.addEventListener('load',()=>setTimeout(()=>{wrapOpenPage();boot();},900));onAuthStateChanged(auth,()=>setTimeout(boot,700));setTimeout(()=>{wrapOpenPage();boot();},1800);
