
import { initializeApp, getApps } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getAuth, onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { getFirestore, collection, doc, getDoc, getDocs, setDoc, addDoc, query, where, orderBy, onSnapshot, serverTimestamp, increment, arrayUnion } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyD80d4bZpZZp0JRZeaBwQKG5GapwLJVki8",authDomain:"kalb-message.firebaseapp.com",projectId:"kalb-message",storageBucket:"kalb-message.firebasestorage.app",messagingSenderId:"139873273901",appId:"1:139873273901:web:c7c079d385daeb3401d0a4",measurementId:"G-C9S0K1SG0D"};
const app=getApps().length?getApps()[0]:initializeApp(firebaseConfig);
const auth=getAuth(app);
const db=getFirestore(app);
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const num=v=>{const n=Number(v||0);return Number.isFinite(n)?Math.max(0,Math.floor(n)):0};
const ts=t=>t?.seconds?new Date(t.seconds*1000):(typeof t==='number'?new Date(t):null);
const fmt=t=>{const d=ts(t);return d?d.toLocaleString():""};
const uidOf=u=>u?.uid||u?.id||"";
const state={user:null,me:null,users:[],posts:[],chats:[],online:{},unsubs:[]};
function byUid(uid){return state.users.find(u=>uidOf(u)===uid)||{};}
function nameOf(u,fallback="User"){return u?.name||u?.displayName||u?.username||String(u?.email||fallback).split('@')[0]||fallback;}
function initial(v,e){const s=(v||e||'U').trim();return s?Array.from(s)[0].toUpperCase():'U';}
function safeBg(u){return u?.avatarColor?"linear-gradient(135deg,#22d3ee,#8b5cf6,#22c55e)":"";}
function archivedChats(){try{return JSON.parse(localStorage.getItem('kalbArchivedChats_'+state.user.uid)||'[]')}catch(e){return[]}}
function deletedMap(){try{return JSON.parse(localStorage.getItem('kalbDeletedChatMap_'+state.user.uid)||'{}')}catch(e){return{}}}
function isDeletedChat(c){const m=deletedMap();const d=m[c.id];if(!d)return false;const updated=((c.lastMessageAt?.seconds)||(c.updatedAt?.seconds)||0)*1000;return !updated||updated<=d;}
function canViewPost(p){if(!state.user)return false;if(p.uid===state.user.uid||p.userId===state.user.uid)return true;const privacy=p.privacy||'public';if(privacy==='private')return false;if(privacy==='friends'){const owner=byUid(p.uid||p.userId);const f1=Array.isArray(owner.friends)?owner.friends:[];const f2=Array.isArray(state.me?.friends)?state.me.friends:[];return f1.includes(state.user.uid)||f2.includes(p.uid||p.userId);}return true;}
function updateDashboard(){
  const total=$('totalUsers'); if(total) total.innerText=state.users.length||0;
  const online=$('onlineUsersCount'); if(online){let n=0; Object.keys(state.online||{}).forEach(uid=>{const u=byUid(uid); if(state.online[uid]?.online===true && u.hideOnline!==true)n++;}); if(!n) n=state.users.filter(u=>u.online===true&&u.hideOnline!==true).length; online.innerText=n;}
  const home=$('homeUser'); if(home && state.me){const followers=Array.isArray(state.me.followers)?state.me.followers.length:num(state.me.followersCount); const following=Array.isArray(state.me.following)?state.me.following.length:num(state.me.followingCount); home.innerText=`${nameOf(state.me)} • @${state.me.username||String(state.me.email||'user').split('@')[0]} • ${followers} followers • following ${following}`;}
}
function renderChats(){
  const box=$('chatList'); if(!box||!state.user)return;
  const search=String($('chatSearchInput')?.value||'').toLowerCase().trim(); const archived=archivedChats();
  let list=state.chats.filter(c=>Array.isArray(c.members)&&c.members.includes(state.user.uid)&&!isDeletedChat(c));
  const wantArchived=(window.chatFilter==='archived')||window.__kalbShowArchivedOnly===true;
  list=list.filter(c=>wantArchived?archived.includes(c.id):!archived.includes(c.id));
  list=list.filter(c=>{const other=(c.members||[]).find(x=>x!==state.user.uid)||''; const u=byUid(other); const n=((c.memberNames&&c.memberNames[other])||nameOf(u)||'User').toLowerCase(); return !search||n.includes(search)||String(c.lastMessage||'').toLowerCase().includes(search);});
  list.sort((a,b)=>((b.lastMessageAt?.seconds)||(b.updatedAt?.seconds)||0)-((a.lastMessageAt?.seconds)||(a.updatedAt?.seconds)||0));
  if(!list.length){box.innerHTML=`<div class="card empty">${wantArchived?'No archived chats.':'No active chats yet.'}</div>`;return;}
  box.innerHTML=list.map(c=>{const other=(c.members||[]).find(x=>x!==state.user.uid)||''; const u=byUid(other); const nm=(c.memberNames&&c.memberNames[other])||nameOf(u,'User'); const isA=archived.includes(c.id); const pin=(c.pinnedBy||[]).includes(state.user.uid);return `<div class="card user-row" data-chat-id="${esc(c.id)}"><div class="avatar" style="${safeBg(u)?`background:${safeBg(u)}`:''}">${esc(u.avatarEmoji||initial(nm,u.email))}</div><div class="user-info"><h3>${esc(nm)} ${isA?'<span class="archived-label">Archived</span>':''} ${pin?'<span class="archived-label">Pinned</span>':''}</h3><p class="muted">${esc(c.lastMessage||'Tap Open to continue chat.')}</p><p class="muted">${fmt(c.lastMessageAt||c.updatedAt)}</p></div><div class="actions"><button class="btn small" onclick="kalbOpenChatFromList('${esc(c.id)}','${esc(other)}')">Open</button>${isA?`<button class="btn small" onclick="unarchiveChat('${esc(c.id)}')">Unarchive</button>`:`<button class="btn small" onclick="archiveChat('${esc(c.id)}')">Archive</button>`}<button class="btn small red" onclick="deleteChatLocal('${esc(c.id)}')">Delete</button></div></div>`;}).join('');
}
function reactionCount(p,e){const r=p.reactions||{}; return Array.isArray(r[e])?r[e].length:0;}
function renderPostsInto(boxId,posts,limit){const box=$(boxId); if(!box)return; let list=(posts||[]).filter(canViewPost); if(limit)list=list.slice(0,limit); if(!list.length){box.innerHTML='<div class="card empty">No posts yet. Be the first to post.</div>';return;} box.innerHTML=list.map(p=>{const uid=p.uid||p.userId||''; const u=byUid(uid); const nm=p.name||nameOf(u,'User'); const un=p.username||u.username||String(p.email||u.email||'user').split('@')[0]; const mine=uid===state.user?.uid; const liked=Array.isArray(p.likes)&&p.likes.includes(state.user.uid); const saved=Array.isArray(p.savedBy)&&p.savedBy.includes(state.user.uid); const emojis=['❤️','😂','😮','😢','👍']; return `<div class="post-box" data-post-id="${esc(p.id)}"><span class="post-pin">${p.privacy==='private'?'🔒 Private':p.privacy==='friends'?'👥 Friends':'🌍 Public'}</span><div class="post-head"><div class="avatar" onclick="viewUserProfile('${esc(uid)}')" style="cursor:pointer;${safeBg(u)?`background:${safeBg(u)}`:''}">${esc(u.avatarEmoji||p.avatarEmoji||initial(nm,p.email))}</div><div class="user-info"><h3>${esc(nm)}</h3><p>@${esc(un)} • ${fmt(p.createdAt)||''}</p><button class="feed-profile-btn" onclick="viewUserProfile('${esc(uid)}')">View Profile</button></div></div><div class="post-text">${esc(p.text||p.content||'')}</div><div class="post-actions"><div class="reaction-row" style="width:100%;display:flex;gap:7px;flex-wrap:wrap">${emojis.map(e=>`<button class="react-btn" onclick="reactToPostFinal('${esc(p.id)}','${e}')">${e} ${reactionCount(p,e)}</button>`).join('')}</div><button class="btn small ${liked?'green':''}" onclick="reactToPostFinal('${esc(p.id)}','❤️')">${liked?'Liked':'Like'} (${Array.isArray(p.likes)?p.likes.length:0})</button><button class="btn small ${saved?'green':''}" onclick="toggleSavePost('${esc(p.id)}')">${saved?'Saved':'Save'}</button><button class="btn small" onclick="repostPost('${esc(p.id)}')">Repost</button>${mine?`<button class="btn small red" onclick="deletePost('${esc(p.id)}')">Delete</button>`:`<button class="btn small red" onclick="reportPost('${esc(p.id)}')">Report</button>`}</div></div>`;}).join('');}
function renderStories(){const box=$('storyStrip'); if(!box)return; const stories=state.posts.filter(p=>p.type==='story'||p.type==='status').sort((a,b)=>((b.createdAt?.seconds)||0)-((a.createdAt?.seconds)||0)).slice(0,12); box.innerHTML=stories.length?stories.map(s=>`<div class="story-item" onclick="openStoryViewer('${esc(s.id)}')"><b>${esc(s.name||nameOf(byUid(s.uid),'User'))}</b><p>${esc(s.text||s.content||'')}</p><small>${Array.isArray(s.views)?s.views.length:0} views</small></div>`).join(''):'<div class="story-item muted">No stories yet.</div>';}
function renderPosts(){const sorted=state.posts.slice().sort((a,b)=>((b.createdAt?.seconds)||0)-((a.createdAt?.seconds)||0)); renderPostsInto('homeFeedBox',sorted,8); renderPostsInto('postsBox',sorted); renderStories();}
async function loadMe(){if(!state.user)return null; try{const s=await getDoc(doc(db,'users',state.user.uid)); state.me=s.exists()?{uid:state.user.uid,...s.data()}:{uid:state.user.uid,email:state.user.email||'',name:state.user.displayName||'User'};}catch(e){state.me={uid:state.user.uid,email:state.user.email||'',name:state.user.displayName||'User'};} return state.me;}
const ACH=[{id:'first_login',icon:'👋',name:'Welcome to Kalb',desc:'Open your account.',check:u=>true},{id:'daily_3',icon:'🔥',name:'3 Day Streak',desc:'Claim streak for 3 days.',check:u=>num(u.kalbStreak)>=3||num(u.kalbBestStreak)>=3},{id:'daily_7',icon:'🏆',name:'7 Day Streak',desc:'Claim streak for 7 days.',check:u=>num(u.kalbStreak)>=7||num(u.kalbBestStreak)>=7},{id:'level_2',icon:'⚡',name:'Level 2',desc:'Reach 100 XP.',check:u=>num(u.kalbXP)>=100},{id:'level_5',icon:'💎',name:'Level 5',desc:'Reach 400 XP.',check:u=>num(u.kalbXP)>=400},{id:'coin_collector',icon:'🪙',name:'Coin Collector',desc:'Collect 100 Kalb Coins.',check:u=>num(u.kalbCoins)>=100},{id:'game_player',icon:'🎮',name:'Game Player',desc:'Earn game XP.',check:u=>num(u.kalbGameXP)>0||u.kalbAchievementFlags?.gamePlayer},{id:'spinner',icon:'🎡',name:'Daily Spinner',desc:'Use the Daily Spin Wheel.',check:u=>num(u.kalbSpinCount)>0||u.kalbAchievementFlags?.spinPlayer}];
function levelFromXP(xp){xp=num(xp);const level=Math.max(1,Math.floor(xp/100)+1);const pct=Math.min(100,Math.round(((xp-(level-1)*100)/100)*100));let title='Newbie'; if(level>=20)title='Legend'; else if(level>=15)title='Elite'; else if(level>=10)title='Star'; else if(level>=5)title='Pro'; else if(level>=3)title='Active'; return{level,title,pct,inside:xp-(level-1)*100};}
function achIds(u){const old=Array.isArray(u?.kalbAchievements)?u.kalbAchievements:[]; return Array.from(new Set([...old,...ACH.filter(a=>{try{return a.check(u||{})}catch(e){return false}}).map(a=>a.id)]));}
function renderAchievements(u){u=u||state.me||{};const lv=levelFromXP(u.kalbXP);const ids=new Set(achIds(u)); if($('kalbLevelBadge'))$('kalbLevelBadge').innerText=lv.level; if($('kalbLevelTitle'))$('kalbLevelTitle').innerText=lv.title; if($('kalbXPCount'))$('kalbXPCount').innerText=num(u.kalbXP); if($('kalbStreakCount'))$('kalbStreakCount').innerText=num(u.kalbStreak); if($('kalbBestStreakCount'))$('kalbBestStreakCount').innerText=num(u.kalbBestStreak); if($('kalbAchievementCount'))$('kalbAchievementCount').innerText=ids.size+'/'+ACH.length; if($('kalbXPFill'))$('kalbXPFill').style.width=lv.pct+'%'; if($('kalbXPLabel'))$('kalbXPLabel').innerText=`${lv.inside} / 100 XP to Level ${lv.level+1}`; if($('kalbLevelProgressLabel'))$('kalbLevelProgressLabel').innerText=lv.pct+'%'; const list=$('kalbAchievementsList'); if(list)list.innerHTML=ACH.map(a=>{const ok=ids.has(a.id);return `<div class="kalb-ach-item ${ok?'unlocked':'locked'}"><div class="kalb-ach-badge">${a.icon}</div><div><h4>${esc(a.name)}</h4><p>${esc(a.desc)}</p><div class="kalb-ach-locked">${ok?'Unlocked':'Locked'}</div></div></div>`}).join(''); const users=state.users.length?state.users:[u]; const lb=$('kalbLevelLeaderboard'); if(lb)lb.innerHTML=users.slice().sort((a,b)=>num(b.kalbXP)-num(a.kalbXP)).slice(0,10).map((x,i)=>{const l=levelFromXP(x.kalbXP);return `<div class="kalb-level-leader-row"><div class="kalb-level-rank">${i+1}</div><div><h4>${esc(nameOf(x))}</h4><p>${num(x.kalbXP)} XP · streak ${num(x.kalbStreak)}</p></div><div class="kalb-level-score">Lv ${l.level}</div></div>`}).join('')||'<div class="empty">No level data yet.</div>';}
function status(msg,bad=false){const box=$('kalbAchievementsStatus');if(box)box.innerHTML=msg?`<div class="notice ${bad?'err':''}">${esc(msg)}</div>`:'';}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function yesterday(){const d=new Date(Date.now()-86400000);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
window.kalbRenderAchievementsSystem=async function(){await loadMe(); renderAchievements(state.me);};
window.kalbShowLevelLeaderboard=function(){renderAchievements(state.me);$('kalbLevelLeaderboard')?.scrollIntoView({behavior:'smooth',block:'nearest'});};
window.kalbClaimDailyStreak=async function(){if(!state.user)return alert('Login first.');const me=await loadMe();const t=today();if(me.kalbLastStreakDate===t){status('You already claimed today. Come back tomorrow.',true);return;}const streak=me.kalbLastStreakDate===yesterday()?num(me.kalbStreak)+1:1;const best=Math.max(num(me.kalbBestStreak),streak);try{await setDoc(doc(db,'users',state.user.uid),{kalbXP:increment(50),kalbCoins:increment(10),kalbStreak:streak,kalbBestStreak:best,kalbLastStreakDate:t,kalbAchievements:arrayUnion(...achIds({...me,kalbStreak:streak,kalbBestStreak:best,kalbXP:num(me.kalbXP)+50})),achievementsUpdatedAt:serverTimestamp()},{merge:true});await loadMe();renderAchievements(state.me);status(`Daily streak claimed! +50 XP and +10 Kalb Coins. Current streak: ${streak}.`);}catch(e){console.error(e);status(e.message||'Daily streak claim failed. Check Firebase rules.',true);}};
async function fallbackCreatePost(type='post'){if(!state.user)return alert('Login first.');const box=type==='story'?($('homePostText')||$('postText')):($('postText')||$('homePostText'));const text=String(box?.value||'').trim();if(!text)return alert('Write something first.');const me=state.me||await loadMe()||{};await addDoc(collection(db,'posts'),{text,content:text,type:type==='story'?'story':'post',uid:state.user.uid,userId:state.user.uid,email:state.user.email||'',name:nameOf(me,state.user.displayName||'User'),username:me.username||String(state.user.email||'user').split('@')[0],likes:[],savedBy:[],commentsCount:0,createdAt:serverTimestamp()});if(box)box.value='';}
function wrapButtons(){if(window.createPost&&!window.createPost.__restoreWrapped){const old=window.createPost;window.createPost=async function(){try{return await old.apply(this,arguments)}finally{setTimeout(refreshOnce,900)}};window.createPost.__restoreWrapped=true;}else if(!window.createPost){window.createPost=()=>fallbackCreatePost('post').then(()=>setTimeout(refreshOnce,600)).catch(e=>alert(e.message));} if(window.createStoryPost&&!window.createStoryPost.__restoreWrapped){const old=window.createStoryPost;window.createStoryPost=async function(){try{return await old.apply(this,arguments)}finally{setTimeout(refreshOnce,900)}};window.createStoryPost.__restoreWrapped=true;}else if(!window.createStoryPost){window.createStoryPost=()=>fallbackCreatePost('story').then(()=>setTimeout(refreshOnce,600)).catch(e=>alert(e.message));} const oldOpen=window.openPage;if(oldOpen&&!oldOpen.__criticalRestoreWrapped){window.openPage=function(id,nav){const r=oldOpen.apply(this,arguments);setTimeout(()=>{renderChats();renderPosts();renderAchievements(state.me);updateDashboard();},250);return r};window.openPage.__criticalRestoreWrapped=true;} const oldChatSearch=$('chatSearchInput'); if(oldChatSearch&&!oldChatSearch.__restoreBound){oldChatSearch.addEventListener('input',renderChats);oldChatSearch.__restoreBound=true;}}
async function refreshOnce(){if(!state.user)return;try{const [us,ps,cs]=await Promise.all([getDocs(collection(db,'users')),getDocs(collection(db,'posts')),getDocs(query(collection(db,'chats'),where('members','array-contains',state.user.uid)))]);state.users=[];us.forEach(d=>state.users.push({uid:d.id,...d.data()}));state.posts=[];ps.forEach(d=>state.posts.push({id:d.id,...d.data()}));state.chats=[];cs.forEach(d=>state.chats.push({id:d.id,...d.data()}));await loadMe();updateDashboard();renderChats();renderPosts();renderAchievements(state.me);}catch(e){console.warn('critical refresh failed',e);}}
function clearUnsubs(){state.unsubs.forEach(fn=>{try{fn()}catch(e){}});state.unsubs=[];}
function startLive(user){clearUnsubs();state.user=user;wrapButtons();loadMe().then(()=>{updateDashboard();renderAchievements(state.me);});try{state.unsubs.push(onSnapshot(collection(db,'users'),snap=>{state.users=[];snap.forEach(d=>state.users.push({uid:d.id,...d.data()}));state.me=state.users.find(x=>uidOf(x)===user.uid)||state.me;updateDashboard();renderChats();renderPosts();renderAchievements(state.me);},e=>console.warn('restore users listener',e)));}catch(e){}try{state.unsubs.push(onSnapshot(collection(db,'onlineUsers'),snap=>{state.online={};snap.forEach(d=>{const x=d.data();state.online[x.uid||d.id]=x;});updateDashboard();},e=>console.warn('restore online listener',e)));}catch(e){}try{state.unsubs.push(onSnapshot(query(collection(db,'chats'),where('members','array-contains',user.uid)),snap=>{state.chats=[];snap.forEach(d=>state.chats.push({id:d.id,...d.data()}));renderChats();},e=>console.warn('restore chats listener',e)));}catch(e){}try{state.unsubs.push(onSnapshot(query(collection(db,'posts'),orderBy('createdAt','desc')),snap=>{state.posts=[];snap.forEach(d=>state.posts.push({id:d.id,...d.data()}));renderPosts();renderAchievements(state.me);},e=>{console.warn('restore ordered posts listener',e);try{onSnapshot(collection(db,'posts'),snap=>{state.posts=[];snap.forEach(d=>state.posts.push({id:d.id,...d.data()}));renderPosts();},console.warn)}catch(_){}}));}catch(e){}setTimeout(refreshOnce,900);setTimeout(refreshOnce,2500);}
onAuthStateChanged(auth,u=>{if(!u){clearUnsubs();return;}startLive(u);});
document.addEventListener('DOMContentLoaded',()=>{wrapButtons();setTimeout(()=>auth.currentUser&&startLive(auth.currentUser),800);});
window.addEventListener('load',()=>setTimeout(()=>{wrapButtons();if(auth.currentUser)refreshOnce();},1200));
window.kalbDataRestoreRefresh=refreshOnce;
